server {
    listen 80;
    listen [::]:80;
    server_name velesvoyage.ru www.velesvoyage.ru www.veles-voyage.ru;
    return 301 https://veles-voyage.ru$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name velesvoyage.ru www.velesvoyage.ru www.veles-voyage.ru;
    ssl_certificate /etc/letsencrypt/live/veles-voyage.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/veles-voyage.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://veles-voyage.ru$request_uri;
}
